name: Node.js CI

on:
  push:
    branches: [ main , patch-1]
  pull_request:
    branches: [ main , patch-1]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      # Removed build step as your project doesn't need it

      - name: Fix test for swapi.dev
        run: |
          echo "Fixing test for swapi.dev..."
          sed -i 's|http://swapi.co/api|https://swapi.dev/api|g' ./server/api/services/response-builder.spec.ts

      - name: Run tests
        run: npm test
