name: CI-CD Pipeline

on:
  push:
    branches: [main, master, patch-1]
  pull_request:
    branches: [main, master, patch-1]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests
        run: npm run test

      - name: Compile the App
        run: npm run compile

      - name: Run Integration Tests
        run: |
          npm run itest:build
          npm run itest:run

      - name: Build Docker Image
        run: docker build -t nxplorerjs-microservice .

      - name: Docker Compose Up
        run: docker-compose up -d

      - name: Verify App Is Running (Optional)
        run: curl --retry 5 --retry-delay 3 http://localhost:3000/healthcheck || true
